---
repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform-fmt
        args: ["-recursive"]
      - id: tflint
        args:
          - "--fix"
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go